site_name: Serviceware ESP online manual
nav:
  - Home: index.md
  - Authenticator:
    - Installation: Authenticator_Installation.md
  - Financial:
    - Installation: Financial_Installation.md
  - Knowledge:
    - Create an article: Knowledge_CreateArticle.md
  - Messaging: 
    - Introduction & Goals: Messaging_Topic1.md
    - Glossary: Messaging_Topic2.md
  - Notifications:
    - Installation: Notifications_Installation.md
  - Performance:
    - Installation: Performance_Installation.md
  - Processes:
    - Installation: Processes_Installation.md
    - Workflow design: Processes_WFDesign.md
  - Resources:
    - Installation: Resources_Installation.md
theme: readthedocs