site_name: Serviceware ESP online manual
nav:
  - Home: index.md
  - Authenticator:
    - Installation: Authenticator_Installation.md
  - Financial:
    - Installation: Financial_Installation.md
  - Knowledge:
    - Create an article: Knowledge_CreateArticle.md
  - Messaging: 
    - Integration: Messaging\integration\support.md
    - Events: Messaging\events\index.md
  - Notifications:
    - Installation: Notifications_Installation.md
  - Performance:
    - Installation: Performance_Installation.md
  - Processes:
    - Installation: Processes\Processes_Installation.md
    - Workflow design: Processes\Processes_WFDesign.md
  - Resources:
    - Installation: Resources_Installation.md
theme: readthedocs